---
title: "P8105 Homework 3"
author: "Junhui Mi"
date: "2019/11/4"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%")

library(tidyverse)
library(ggridges)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

# Problem 1

```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

replace_missing = function(x) {
    if (is.numeric(x)) {
    x[is.na(x)] = mean(x, na.rm = TRUE)
      }
    x[is.na(x)] = "virginica"
    x
}

iris_without_missing_list = map(iris_with_missing, replace_missing)

iris_without_missing_tibble = map_dfr(iris_with_missing, replace_missing)

iris_without_missing_tibble
```


# Problem 2

```{r}
con_exp = list.files("./data", full.names = TRUE)

load_and_tidy = function(path) {
  df = read_csv(path) %>%
    janitor::clean_names() %>%
    mutate(
        arm = str_sub(path, 8, 10),
        id = str_sub(path, 12, 13),
        arm = str_replace_all(arm, c("con" = "control", "exp" = "experiment"))) %>%
    select(id, arm, week_1:week_8)
  df
}

observation_data = map_df(.x = con_exp, ~ load_and_tidy(.x))

observation_data

observation_data %>%
  gather(key = week, value = observation, week_1:week_8) %>%
  mutate(week = str_replace(week, "week_", "")) %>%
  ggplot(aes(x = week, y = observation, color = id, group = id)) +
  geom_point() + geom_line() + facet_grid(~arm) + 
  labs(title = "Spaghetti Plot of Experiment Arms and Control Arms")
```

# Problem 3

```{r}
set.seed(1)

sim_regression = function(n = 30, beta0 = 2, beta1) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 0, sd = 1),
    y = beta0 + beta1 * x + rnorm(30, 0, sqrt(50))
  )
  
  ls = lm(y ~ x, data = sim_data)
  
  tibble(
    beta1_hat = coef(ls)[2],
    p_value = pull(broom::tidy(ls),p.value)[[2]]
  )
}

output = 
  tibble(beta1_value = c(0:6)) %>% 
  mutate(
    output_list = map(.x = beta1_value,
                      ~rerun(10000, sim_regression(beta1 = .x))),
    estimate_df = map(output_list, bind_rows)) %>% 
  select(-output_list) %>% 
  unnest(estimate_df)

output %>% 
  filter(p_value < 0.05) %>%
  group_by(beta1_value) %>%
  summarize(proportion = n()/10000) %>%
  ggplot(aes(x = beta1_value, y = proportion)) + 
    geom_point() + geom_smooth(se = FALSE) +
  scale_x_continuous(breaks = c(0,1,2,3,4,5,6)) +
  labs(title = "Association between effect size and power", 
       x = "true value of beta1",
       y = "proportion of rejected nulls")

beta1_estimate = output %>%
  group_by(beta1_value) %>%
  summarize(average_beta1_hat = mean(beta1_hat))

ggplot(data = beta1_estimate,
       aes(x = beta1_value, y = average_beta1_hat)) + 
    geom_point() + geom_smooth(se = FALSE) +
  scale_x_continuous(breaks = c(0,1,2,3,4,5,6)) +
  scale_y_continuous(breaks = c(0,1,2,3,4,5,6)) +
  labs(title = "Plot of beta1 estimation", 
       x = "true value of beta1",
       y = "average estimation of beta1") +
  viridis::scale_color_viridis(
    name = "sample scale", 
    discrete = TRUE) 

output %>%
  filter(p_value < 0.05) %>%
  group_by(beta1_value) %>%
  summarize(average_beta1_hat_rejected = mean(beta1_hat)) %>%
  ggplot(aes(x = beta1_value,
             y = average_beta1_hat_rejected)) + 
    geom_point(color = 2) + geom_smooth(se = FALSE) +
  geom_point(data = beta1_estimate,
             y = pull(beta1_estimate, average_beta1_hat),
             color = "black") +
  scale_x_continuous(breaks = c(0,1,2,3,4,5,6)) +
  scale_y_continuous(breaks = c(0,1,2,3,4,5,6)) +
  labs(title = "Plot of beta1 estimation which the null was rejected", 
       x = "true value of beta1",
       y = "average estimation of beta1 which the null was rejected")
```

